
version: '3.8'

services:
  app:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      # Mount storage directory for persistent data
      - ${STORAGE_PATH:-./storage}:/app/storage
      # Mount models directory for model weights
      - ${MODELS_PATH:-./features/yolov11/weights}:/app/features/yolov11/weights
    environment:
      - PYTHONPATH=${PYTHONPATH:-/app}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE:-1}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./storage/detection.db}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS:-.jpg,.jpeg,.png,.bmp,.tiff}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

 